openapi: 3.0.1
info:
  title: Todo-Listen-Verwaltung
  description: Server-Anwendung, mit deren Hilfe Todo-Listen mit entsprechenden Eintraegen erstellt und bearbeitet werden koennen.
  contact:
    email: bartel@rasche-wessler.de
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0
servers:
- url: http://127.0.0.1:5000/
tags:
- name: Listenverwaltung
paths:
  /todo-list/{list_id}:
    get:
      tags:
      - Listenverwaltung
      summary: Get all items from list
      operationId: getList
      parameters:
      - name: list_id
        in: path
        description: list id
        required: true
        schema:
          type: string
      responses:
        200:
          description: List item returned
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoEntry'
        404:
          description: Invalid list id
          content: {}
    delete:
      tags:
      - Listenverwaltung
      summary: Delete a list
      operationId: deleteList
      parameters:
      - name: list_id
        in: path
        description: list id
        required: true
        schema:
          type: string
      responses:
        200:
          description: List was deleted
          content: {}
        404:
          description: Invalid list id
          content: {}
  /todo-list:
    post:
      tags:
      - Listenverwaltung
      summary: Add new list
      operationId: addList
      requestBody:
        description: list object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoList'
        required: true
      responses:
        200:
          description: List added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoList'
        500:
          description: List could not be added
          content: {}
      x-codegen-request-body-name: body
  /todo-list/{list_id}/entry:
    post:
      tags:
      - Listenverwaltung
      summary: Add new entry to existing list
      operationId: addEntry
      parameters:
      - name: list_id
        in: path
        description: list id
        required: true
        schema:
          type: string
      requestBody:
        description: entry object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoEntry'
        required: true
      responses:
        200:
          description: entry added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoEntry'
        400:
          description: request has incorrect format
          content: {}
        500:
          description: entry could not be added
          content: {}   
  /todo-list/{list_id}/entry{entry_id}:
    put:
      tags:
      - Listenverwaltung
      summary: updates an existing entry
      operationId: updateEntry
      parameters:
      - name: list_id
        in: path
        description: list id
        required: true
        schema:
          type: string
      - name: entry_id
        in: path
        description: entry id
        required: true
        schema:
          type: string
      requestBody:
        description: entry object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoEntry'
        required: true
      responses:
        200:
          description: entry updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoEntry'
        400:
          description: request has incorrect format
          content: {}
        404:
          description: id not found
          content: {}
        500:
          description: entry could not be added
          content: {}   
    delete:
      tags:
      - Listenverwaltung
      summary: deletes an existing entry
      operationId: deleteEntry
      parameters:
      - name: list_id
        in: path
        description: list id
        required: true
        schema:
          type: string
      - name: entry_id
        in: path
        description: entry id
        required: true
        schema:
          type: string
      responses:
        200:
          description: entry deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageSuccess'
        404:
          description: id not found
          content: {}
        500:
          description: entry could not be added
          content: {}   
  /todo-list/{list_id}/entries:
    get:
      tags:
      - Listenverwaltung
      summary: get all entries from a list
      operationId: getEntries
      parameters:
      - name: list_id
        in: path
        description: list id
        required: true
        schema:
          type: string
      responses:
        200:
          description: entries returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoEntry'
        404:
          description: id not found
          content: {}
        500:
          description: entry could not be added
          content: {}
  /todo-lists:
    get:
      tags:
      - Listenverwaltung
      summary: get all lists
      operationId: getLists
      responses:
        200:
          description: entries returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoList'
        500:
          description: entry could not be added
          content: {}
components:
  schemas:
    TodoList:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
    TodoEntry:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        user_id:
          type: string
          format: uuid
        list_id:
          type: string
          format: uuid
    MessageSuccess:
      type: object
      properties:
        msg:
          type: string
